// import Table_Item from "./Table_Item"
import "./Table_List.css"

//
// Контейнер с расписаниями
//

{/*return <Table_Item/> */}

export default function Table_List() {
    return <div className="scrollable_table">
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Должность</th>
                    <th>Отдел</th>
                    <th>Зарплата</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Иван</td>
                    <td>Петров</td>
                    <td>Разработчик</td>
                    <td>IT</td>
                    <td>50000</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Мария</td>
                    <td>Сидорова</td>
                    <td>Дизайнер</td>
                    <td>Маркетинг</td>
                    <td>45000</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Алексей</td>
                    <td>Козлов</td>
                    <td>Менеджер</td>
                    <td>Продажи</td>
                    <td>55000</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Ольга</td>
                    <td>Иванова</td>
                    <td>Аналитик</td>
                    <td>Финансы</td>
                    <td>60000</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>Дмитрий</td>
                    <td>Смирнов</td>
                    <td>Тестировщик</td>
                    <td>IT</td>
                    <td>40000</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>Елена</td>
                    <td>Кузнецова</td>
                    <td>HR</td>
                    <td>Персонал</td>
                    <td>48000</td>
                </tr>
            </tbody>
        </table>

        <table>
            <thead>
                <tr>
                    <th>№</th>
                    <th>Продукт</th>
                    <th>Категория</th>
                    <th>Цена</th>
                    <th>Количество</th>
                    <th>Склад</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Ноутбук</td>
                    <td>Электроника</td>
                    <td>50000</td>
                    <td>15</td>
                    <td>А</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Смартфон</td>
                    <td>Электроника</td>
                    <td>30000</td>
                    <td>25</td>
                    <td>Б</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Стул</td>
                    <td>Мебель</td>
                    <td>5000</td>
                    <td>40</td>
                    <td>В</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Книга</td>
                    <td>Канцелярия</td>
                    <td>500</td>
                    <td>100</td>
                    <td>Г</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>Кофе</td>
                    <td>Продукты</td>
                    <td>300</td>
                    <td>50</td>
                    <td>Д</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>Рюкзак</td>
                    <td>Аксессуары</td>
                    <td>2000</td>
                    <td>30</td>
                    <td>А</td>
                </tr>
            </tbody>
        </table>

        <table>
            <thead>
                <tr>
                    <th>Дата</th>
                    <th>Город</th>
                    <th>Температура</th>
                    <th>Влажность</th>
                    <th>Ветер</th>
                    <th>Осадки</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>01.01.2024</td>
                    <td>Москва</td>
                    <td>-5°C</td>
                    <td>80%</td>
                    <td>3 м/с</td>
                    <td>Снег</td>
                </tr>
                <tr>
                    <td>02.01.2024</td>
                    <td>СПб</td>
                    <td>-3°C</td>
                    <td>75%</td>
                    <td>5 м/с</td>
                    <td>Дождь</td>
                </tr>
                <tr>
                    <td>03.01.2024</td>
                    <td>Сочи</td>
                    <td>+10°C</td>
                    <td>65%</td>
                    <td>2 м/с</td>
                    <td>Ясно</td>
                </tr>
                <tr>
                    <td>04.01.2024</td>
                    <td>Екатеринбург</td>
                    <td>-8°C</td>
                    <td>70%</td>
                    <td>4 м/с</td>
                    <td>Облачно</td>
                </tr>
                <tr>
                    <td>05.01.2024</td>
                    <td>Новосибирск</td>
                    <td>-12°C</td>
                    <td>85%</td>
                    <td>6 м/с</td>
                    <td>Снег</td>
                </tr>
                <tr>
                    <td>06.01.2024</td>
                    <td>Калининград</td>
                    <td>0°C</td>
                    <td>78%</td>
                    <td>7 м/с</td>
                    <td>Туман</td>
                </tr>
            </tbody>
        </table>

        <table>
            <thead>
                <tr>
                    <th>Код</th>
                    <th>Студент</th>
                    <th>Математика</th>
                    <th>Физика</th>
                    <th>Химия</th>
                    <th>Средний балл</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>S001</td>
                    <td>Анна В.</td>
                    <td>5</td>
                    <td>4</td>
                    <td>5</td>
                    <td>4.67</td>
                </tr>
                <tr>
                    <td>S002</td>
                    <td>Петр К.</td>
                    <td>4</td>
                    <td>5</td>
                    <td>4</td>
                    <td>4.33</td>
                </tr>
                <tr>
                    <td>S003</td>
                    <td>Сергей М.</td>
                    <td>3</td>
                    <td>4</td>
                    <td>3</td>
                    <td>3.33</td>
                </tr>
                <tr>
                    <td>S004</td>
                    <td>Ольга П.</td>
                    <td>5</td>
                    <td>5</td>
                    <td>5</td>
                    <td>5.00</td>
                </tr>
                <tr>
                    <td>S005</td>
                    <td>Дмитрий С.</td>
                    <td>4</td>
                    <td>3</td>
                    <td>4</td>
                    <td>3.67</td>
                </tr>
                <tr>
                    <td>S006</td>
                    <td>Елена Т.</td>
                    <td>5</td>
                    <td>4</td>
                    <td>4</td>
                    <td>4.33</td>
                </tr>
            </tbody>
        </table>

        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Должность</th>
                    <th>Отдел</th>
                    <th>Зарплата</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Иван</td>
                    <td>Петров</td>
                    <td>Разработчик</td>
                    <td>IT</td>
                    <td>50000</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Мария</td>
                    <td>Сидорова</td>
                    <td>Дизайнер</td>
                    <td>Маркетинг</td>
                    <td>45000</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Алексей</td>
                    <td>Козлов</td>
                    <td>Менеджер</td>
                    <td>Продажи</td>
                    <td>55000</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Ольга</td>
                    <td>Иванова</td>
                    <td>Аналитик</td>
                    <td>Финансы</td>
                    <td>60000</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>Дмитрий</td>
                    <td>Смирнов</td>
                    <td>Тестировщик</td>
                    <td>IT</td>
                    <td>40000</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>Елена</td>
                    <td>Кузнецова</td>
                    <td>HR</td>
                    <td>Персонал</td>
                    <td>48000</td>
                </tr>
            </tbody>
        </table>

        <table>
            <thead>
                <tr>
                    <th>№</th>
                    <th>Продукт</th>
                    <th>Категория</th>
                    <th>Цена</th>
                    <th>Количество</th>
                    <th>Склад</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Ноутбук</td>
                    <td>Электроника</td>
                    <td>50000</td>
                    <td>15</td>
                    <td>А</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Смартфон</td>
                    <td>Электроника</td>
                    <td>30000</td>
                    <td>25</td>
                    <td>Б</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Стул</td>
                    <td>Мебель</td>
                    <td>5000</td>
                    <td>40</td>
                    <td>В</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Книга</td>
                    <td>Канцелярия</td>
                    <td>500</td>
                    <td>100</td>
                    <td>Г</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>Кофе</td>
                    <td>Продукты</td>
                    <td>300</td>
                    <td>50</td>
                    <td>Д</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>Рюкзак</td>
                    <td>Аксессуары</td>
                    <td>2000</td>
                    <td>30</td>
                    <td>А</td>
                </tr>
            </tbody>
        </table>

        <table>
            <thead>
                <tr>
                    <th>Дата</th>
                    <th>Город</th>
                    <th>Температура</th>
                    <th>Влажность</th>
                    <th>Ветер</th>
                    <th>Осадки</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>01.01.2024</td>
                    <td>Москва</td>
                    <td>-5°C</td>
                    <td>80%</td>
                    <td>3 м/с</td>
                    <td>Снег</td>
                </tr>
                <tr>
                    <td>02.01.2024</td>
                    <td>СПб</td>
                    <td>-3°C</td>
                    <td>75%</td>
                    <td>5 м/с</td>
                    <td>Дождь</td>
                </tr>
                <tr>
                    <td>03.01.2024</td>
                    <td>Сочи</td>
                    <td>+10°C</td>
                    <td>65%</td>
                    <td>2 м/с</td>
                    <td>Ясно</td>
                </tr>
                <tr>
                    <td>04.01.2024</td>
                    <td>Екатеринбург</td>
                    <td>-8°C</td>
                    <td>70%</td>
                    <td>4 м/с</td>
                    <td>Облачно</td>
                </tr>
                <tr>
                    <td>05.01.2024</td>
                    <td>Новосибирск</td>
                    <td>-12°C</td>
                    <td>85%</td>
                    <td>6 м/с</td>
                    <td>Снег</td>
                </tr>
                <tr>
                    <td>06.01.2024</td>
                    <td>Калининград</td>
                    <td>0°C</td>
                    <td>78%</td>
                    <td>7 м/с</td>
                    <td>Туман</td>
                </tr>
            </tbody>
        </table>

        <table>
            <thead>
                <tr>
                    <th>Код</th>
                    <th>Студент</th>
                    <th>Математика</th>
                    <th>Физика</th>
                    <th>Химия</th>
                    <th>Средний балл</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>S001</td>
                    <td>Анна В.</td>
                    <td>5</td>
                    <td>4</td>
                    <td>5</td>
                    <td>4.67</td>
                </tr>
                <tr>
                    <td>S002</td>
                    <td>Петр К.</td>
                    <td>4</td>
                    <td>5</td>
                    <td>4</td>
                    <td>4.33</td>
                </tr>
                <tr>
                    <td>S003</td>
                    <td>Сергей М.</td>
                    <td>3</td>
                    <td>4</td>
                    <td>3</td>
                    <td>3.33</td>
                </tr>
                <tr>
                    <td>S004</td>
                    <td>Ольга П.</td>
                    <td>5</td>
                    <td>5</td>
                    <td>5</td>
                    <td>5.00</td>
                </tr>
                <tr>
                    <td>S005</td>
                    <td>Дмитрий С.</td>
                    <td>4</td>
                    <td>3</td>
                    <td>4</td>
                    <td>3.67</td>
                </tr>
                <tr>
                    <td>S006</td>
                    <td>Елена Т.</td>
                    <td>5</td>
                    <td>4</td>
                    <td>4</td>
                    <td>4.33</td>
                </tr>
            </tbody>
        </table>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Должность</th>
                    <th>Отдел</th>
                    <th>Зарплата</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Иван</td>
                    <td>Петров</td>
                    <td>Разработчик</td>
                    <td>IT</td>
                    <td>50000</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Мария</td>
                    <td>Сидорова</td>
                    <td>Дизайнер</td>
                    <td>Маркетинг</td>
                    <td>45000</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Алексей</td>
                    <td>Козлов</td>
                    <td>Менеджер</td>
                    <td>Продажи</td>
                    <td>55000</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Ольга</td>
                    <td>Иванова</td>
                    <td>Аналитик</td>
                    <td>Финансы</td>
                    <td>60000</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>Дмитрий</td>
                    <td>Смирнов</td>
                    <td>Тестировщик</td>
                    <td>IT</td>
                    <td>40000</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>Елена</td>
                    <td>Кузнецова</td>
                    <td>HR</td>
                    <td>Персонал</td>
                    <td>48000</td>
                </tr>
            </tbody>
        </table>

        <table>
            <thead>
                <tr>
                    <th>№</th>
                    <th>Продукт</th>
                    <th>Категория</th>
                    <th>Цена</th>
                    <th>Количество</th>
                    <th>Склад</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Ноутбук</td>
                    <td>Электроника</td>
                    <td>50000</td>
                    <td>15</td>
                    <td>А</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Смартфон</td>
                    <td>Электроника</td>
                    <td>30000</td>
                    <td>25</td>
                    <td>Б</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Стул</td>
                    <td>Мебель</td>
                    <td>5000</td>
                    <td>40</td>
                    <td>В</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Книга</td>
                    <td>Канцелярия</td>
                    <td>500</td>
                    <td>100</td>
                    <td>Г</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>Кофе</td>
                    <td>Продукты</td>
                    <td>300</td>
                    <td>50</td>
                    <td>Д</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>Рюкзак</td>
                    <td>Аксессуары</td>
                    <td>2000</td>
                    <td>30</td>
                    <td>А</td>
                </tr>
            </tbody>
        </table>

        <table>
            <thead>
                <tr>
                    <th>Дата</th>
                    <th>Город</th>
                    <th>Температура</th>
                    <th>Влажность</th>
                    <th>Ветер</th>
                    <th>Осадки</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>01.01.2024</td>
                    <td>Москва</td>
                    <td>-5°C</td>
                    <td>80%</td>
                    <td>3 м/с</td>
                    <td>Снег</td>
                </tr>
                <tr>
                    <td>02.01.2024</td>
                    <td>СПб</td>
                    <td>-3°C</td>
                    <td>75%</td>
                    <td>5 м/с</td>
                    <td>Дождь</td>
                </tr>
                <tr>
                    <td>03.01.2024</td>
                    <td>Сочи</td>
                    <td>+10°C</td>
                    <td>65%</td>
                    <td>2 м/с</td>
                    <td>Ясно</td>
                </tr>
                <tr>
                    <td>04.01.2024</td>
                    <td>Екатеринбург</td>
                    <td>-8°C</td>
                    <td>70%</td>
                    <td>4 м/с</td>
                    <td>Облачно</td>
                </tr>
                <tr>
                    <td>05.01.2024</td>
                    <td>Новосибирск</td>
                    <td>-12°C</td>
                    <td>85%</td>
                    <td>6 м/с</td>
                    <td>Снег</td>
                </tr>
                <tr>
                    <td>06.01.2024</td>
                    <td>Калининград</td>
                    <td>0°C</td>
                    <td>78%</td>
                    <td>7 м/с</td>
                    <td>Туман</td>
                </tr>
            </tbody>
        </table>

        <table>
            <thead>
                <tr>
                    <th>Код</th>
                    <th>Студент</th>
                    <th>Математика</th>
                    <th>Физика</th>
                    <th>Химия</th>
                    <th>Средний балл</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>S001</td>
                    <td>Анна В.</td>
                    <td>5</td>
                    <td>4</td>
                    <td>5</td>
                    <td>4.67</td>
                </tr>
                <tr>
                    <td>S002</td>
                    <td>Петр К.</td>
                    <td>4</td>
                    <td>5</td>
                    <td>4</td>
                    <td>4.33</td>
                </tr>
                <tr>
                    <td>S003</td>
                    <td>Сергей М.</td>
                    <td>3</td>
                    <td>4</td>
                    <td>3</td>
                    <td>3.33</td>
                </tr>
                <tr>
                    <td>S004</td>
                    <td>Ольга П.</td>
                    <td>5</td>
                    <td>5</td>
                    <td>5</td>
                    <td>5.00</td>
                </tr>
                <tr>
                    <td>S005</td>
                    <td>Дмитрий С.</td>
                    <td>4</td>
                    <td>3</td>
                    <td>4</td>
                    <td>3.67</td>
                </tr>
                <tr>
                    <td>S006</td>
                    <td>Елена Т.</td>
                    <td>5</td>
                    <td>4</td>
                    <td>4</td>
                    <td>4.33</td>
                </tr>
            </tbody>
        </table>

        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Должность</th>
                    <th>Отдел</th>
                    <th>Зарплата</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Иван</td>
                    <td>Петров</td>
                    <td>Разработчик</td>
                    <td>IT</td>
                    <td>50000</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Мария</td>
                    <td>Сидорова</td>
                    <td>Дизайнер</td>
                    <td>Маркетинг</td>
                    <td>45000</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Алексей</td>
                    <td>Козлов</td>
                    <td>Менеджер</td>
                    <td>Продажи</td>
                    <td>55000</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Ольга</td>
                    <td>Иванова</td>
                    <td>Аналитик</td>
                    <td>Финансы</td>
                    <td>60000</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>Дмитрий</td>
                    <td>Смирнов</td>
                    <td>Тестировщик</td>
                    <td>IT</td>
                    <td>40000</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>Елена</td>
                    <td>Кузнецова</td>
                    <td>HR</td>
                    <td>Персонал</td>
                    <td>48000</td>
                </tr>
            </tbody>
        </table>

        <table>
            <thead>
                <tr>
                    <th>№</th>
                    <th>Продукт</th>
                    <th>Категория</th>
                    <th>Цена</th>
                    <th>Количество</th>
                    <th>Склад</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Ноутбук</td>
                    <td>Электроника</td>
                    <td>50000</td>
                    <td>15</td>
                    <td>А</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Смартфон</td>
                    <td>Электроника</td>
                    <td>30000</td>
                    <td>25</td>
                    <td>Б</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Стул</td>
                    <td>Мебель</td>
                    <td>5000</td>
                    <td>40</td>
                    <td>В</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Книга</td>
                    <td>Канцелярия</td>
                    <td>500</td>
                    <td>100</td>
                    <td>Г</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>Кофе</td>
                    <td>Продукты</td>
                    <td>300</td>
                    <td>50</td>
                    <td>Д</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>Рюкзак</td>
                    <td>Аксессуары</td>
                    <td>2000</td>
                    <td>30</td>
                    <td>А</td>
                </tr>
            </tbody>
        </table>

        <table>
            <thead>
                <tr>
                    <th>Дата</th>
                    <th>Город</th>
                    <th>Температура</th>
                    <th>Влажность</th>
                    <th>Ветер</th>
                    <th>Осадки</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>01.01.2024</td>
                    <td>Москва</td>
                    <td>-5°C</td>
                    <td>80%</td>
                    <td>3 м/с</td>
                    <td>Снег</td>
                </tr>
                <tr>
                    <td>02.01.2024</td>
                    <td>СПб</td>
                    <td>-3°C</td>
                    <td>75%</td>
                    <td>5 м/с</td>
                    <td>Дождь</td>
                </tr>
                <tr>
                    <td>03.01.2024</td>
                    <td>Сочи</td>
                    <td>+10°C</td>
                    <td>65%</td>
                    <td>2 м/с</td>
                    <td>Ясно</td>
                </tr>
                <tr>
                    <td>04.01.2024</td>
                    <td>Екатеринбург</td>
                    <td>-8°C</td>
                    <td>70%</td>
                    <td>4 м/с</td>
                    <td>Облачно</td>
                </tr>
                <tr>
                    <td>05.01.2024</td>
                    <td>Новосибирск</td>
                    <td>-12°C</td>
                    <td>85%</td>
                    <td>6 м/с</td>
                    <td>Снег</td>
                </tr>
                <tr>
                    <td>06.01.2024</td>
                    <td>Калининград</td>
                    <td>0°C</td>
                    <td>78%</td>
                    <td>7 м/с</td>
                    <td>Туман</td>
                </tr>
            </tbody>
        </table>

        <table>
            <thead>
                <tr>
                    <th>Код</th>
                    <th>Студент</th>
                    <th>Математика</th>
                    <th>Физика</th>
                    <th>Химия</th>
                    <th>Средний балл</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>S001</td>
                    <td>Анна В.</td>
                    <td>5</td>
                    <td>4</td>
                    <td>5</td>
                    <td>4.67</td>
                </tr>
                <tr>
                    <td>S002</td>
                    <td>Петр К.</td>
                    <td>4</td>
                    <td>5</td>
                    <td>4</td>
                    <td>4.33</td>
                </tr>
                <tr>
                    <td>S003</td>
                    <td>Сергей М.</td>
                    <td>3</td>
                    <td>4</td>
                    <td>3</td>
                    <td>3.33</td>
                </tr>
                <tr>
                    <td>S004</td>
                    <td>Ольга П.</td>
                    <td>5</td>
                    <td>5</td>
                    <td>5</td>
                    <td>5.00</td>
                </tr>
                <tr>
                    <td>S005</td>
                    <td>Дмитрий С.</td>
                    <td>4</td>
                    <td>3</td>
                    <td>4</td>
                    <td>3.67</td>
                </tr>
                <tr>
                    <td>S006</td>
                    <td>Елена Т.</td>
                    <td>5</td>
                    <td>4</td>
                    <td>4</td>
                    <td>4.33</td>
                </tr>
            </tbody>
        </table>
    </div>
}